---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
    name: cluster-admins
users:
    - larsks
    - rob-baron
    - naved001
    - tumido
    - HumairAK
    - ipolonsk
    - durandom
    - cdoan1
    - 4n4nd
