---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - workflow-controller-configmap.yaml

patchesJson6902:
  - path: argo-server.yaml
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1
